In [ ]:
import torch

In [ ]:
print(torch.__version__)

2.5.1+cu121


In [ ]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. using CPU")

GPU is available
Using GPU: Tesla T4


In [ ]:
# using empty

In [ ]:
torch.empty(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
e = torch.randint(size = (2,3), low = 1, high = 10, dtype = torch.float32)

In [ ]:
e

tensor([[5., 9., 5.],
        [6., 1., 7.]])

In [ ]:
torch.std(e)

tensor(2.6646)

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device('cuda')

In [ ]:
# creating a new tensor on GPU

In [ ]:
torch.rand((2,3), device = device)

tensor([[0.6721, 0.5988, 0.9632],
        [0.1382, 0.0510, 0.9371]], device='cuda:0')

In [ ]:
# moving an existing tensor to GPU

In [ ]:
e

tensor([[5., 9., 5.],
        [6., 1., 7.]])

In [ ]:
 a = e.to(device)

In [ ]:
a

tensor([[5., 9., 5.],
        [6., 1., 7.]], device='cuda:0')

In [ ]:
a + 5

tensor([[10., 14., 10.],
        [11.,  6., 12.]], device='cuda:0')

In [ ]:
import time

# define the size of matrices

size = 10000

# create random matrices on CPU
matrix_cpu1 = torch.randn(size,size)
matrix_cpu2 = torch.randn(size,size)

# measure the time on CPU

start_time = time.time()

result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)

cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time: .4f} seconds")

# move matrices to GPU

matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')


#measure time on GPU

start_time = time.time()

result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)

torch.cuda.synchronize()  # Ensure all GPU operations are complete

gpu_time = time.time() - start_time

print(f"Time on GPU: {gpu_time: .4f} seconds")

# compare results

print("\n speedup (cpu_time / gpu_time): ", cpu_time/gpu_time)

Time on CPU:  15.6507 seconds
Time on GPU:  0.6261 seconds

 speedup (cpu_time / gpu_time):  24.996919741150112


In [ ]:
torch.log(e)

tensor([[1.6094, 2.1972, 1.6094],
        [1.7918, 0.0000, 1.9459]])

In [ ]:
torch.sqrt(e)

tensor([[2.2361, 3.0000, 2.2361],
        [2.4495, 1.0000, 2.6458]])

In [ ]:
torch.sigmoid(e)

tensor([[0.9933, 0.9999, 0.9933],
        [0.9975, 0.7311, 0.9991]])

In [ ]:
torch.softmax(e, dim=0)

tensor([[2.6894e-01, 9.9966e-01, 1.1920e-01],
        [7.3106e-01, 3.3535e-04, 8.8080e-01]])

In [ ]:
torch.relu(e)

tensor([[5., 9., 5.],
        [6., 1., 7.]])

In [ ]:
# inplace operation

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

In [ ]:
m

tensor([[0.8420, 0.1127, 0.1009],
        [0.5662, 0.0351, 0.7615]])

In [ ]:
n

tensor([[0.5597, 0.4290, 0.8488],
        [0.6378, 0.4015, 0.5144]])

In [ ]:
m + n

tensor([[1.4017, 0.5417, 0.9497],
        [1.2040, 0.4366, 1.2759]])

In [ ]:
m.add(n)

tensor([[1.4017, 0.5417, 0.9497],
        [1.2040, 0.4366, 1.2759]])

In [ ]:
m

tensor([[0.8420, 0.1127, 0.1009],
        [0.5662, 0.0351, 0.7615]])

In [ ]:
m.add_(n)

tensor([[1.4017, 0.5417, 0.9497],
        [1.2040, 0.4366, 1.2759]])

In [ ]:
m

tensor([[1.4017, 0.5417, 0.9497],
        [1.2040, 0.4366, 1.2759]])

In [ ]:
e.relu_()

tensor([[5., 9., 5.],
        [6., 1., 7.]])

In [ ]:
# copying a Tensor

In [ ]:
a = torch.rand(2,3)

In [ ]:
a

tensor([[0.1721, 0.1905, 0.0356],
        [0.9626, 0.3642, 0.9363]])

In [ ]:
b = a

In [ ]:
b

tensor([[0.0000, 0.1905, 0.0356],
        [0.9626, 0.3642, 0.9363]])

In [ ]:
a[0][0] = 0

In [ ]:
a

tensor([[0.0000, 0.1905, 0.0356],
        [0.9626, 0.3642, 0.9363]])

In [ ]:
b

tensor([[0.0000, 0.1905, 0.0356],
        [0.9626, 0.3642, 0.9363]])

In [ ]:
id(a)

138526705274848

In [ ]:
id(b)

138526705274848

In [ ]:
b = a.clone()

In [ ]:
b

tensor([[0.0000, 0.1905, 0.0356],
        [0.9626, 0.3642, 0.9363]])

In [ ]:
a[0][0] = 10

In [ ]:
a

tensor([[10.0000,  0.1905,  0.0356],
        [ 0.9626,  0.3642,  0.9363]])

In [ ]:
b

tensor([[0.0000, 0.1905, 0.0356],
        [0.9626, 0.3642, 0.9363]])

In [ ]:
id(a)

138526705274848

In [ ]:
id(b)

138522822144096

In [ ]:
# Reshaping Tensors

In [ ]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
# flatten

In [ ]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b = torch.rand(2,3,4)

b

tensor([[[0.1594, 0.1547, 0.9159, 0.2845],
         [0.6921, 0.5657, 0.4315, 0.7122],
         [0.1515, 0.9552, 0.7234, 0.7289]],

        [[0.7893, 0.0106, 0.1248, 0.0240],
         [0.1850, 0.1771, 0.5167, 0.2698],
         [0.2718, 0.2982, 0.3808, 0.5947]]])

In [ ]:
b.permute(2,0,1)

tensor([[[0.1594, 0.6921, 0.1515],
         [0.7893, 0.1850, 0.2718]],

        [[0.1547, 0.5657, 0.9552],
         [0.0106, 0.1771, 0.2982]],

        [[0.9159, 0.4315, 0.7234],
         [0.1248, 0.5167, 0.3808]],

        [[0.2845, 0.7122, 0.7289],
         [0.0240, 0.2698, 0.5947]]])

In [ ]:
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [ ]:
# unsqueeze

In [ ]:
c = torch.rand(226,226,3)

In [ ]:
c

tensor([[[0.8713, 0.0648, 0.4597],
         [0.7001, 0.5456, 0.9379],
         [0.7735, 0.3067, 0.0288],
         ...,
         [0.1679, 0.7026, 0.2474],
         [0.4765, 0.1622, 0.3424],
         [0.3077, 0.9497, 0.1641]],

        [[0.8906, 0.6174, 0.1665],
         [0.2636, 0.3008, 0.6062],
         [0.8872, 0.7250, 0.5632],
         ...,
         [0.6697, 0.9905, 0.0327],
         [0.0632, 0.3278, 0.9328],
         [0.4228, 0.2468, 0.5798]],

        [[0.7631, 0.7995, 0.8326],
         [0.5984, 0.3041, 0.9803],
         [0.0416, 0.8722, 0.9415],
         ...,
         [0.3593, 0.4594, 0.9320],
         [0.9534, 0.8105, 0.4385],
         [0.0342, 0.6590, 0.9808]],

        ...,

        [[0.2054, 0.1469, 0.5038],
         [0.3029, 0.2087, 0.4414],
         [0.0997, 0.8424, 0.5975],
         ...,
         [0.1474, 0.2429, 0.7641],
         [0.8260, 0.7502, 0.2584],
         [0.2267, 0.4827, 0.1979]],

        [[0.5549, 0.3148, 0.1151],
         [0.7420, 0.1601, 0.9530],
         [0.

In [ ]:
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [ ]:
c.unsqueeze(1).shape

torch.Size([226, 1, 226, 3])

In [ ]:
c.unsqueeze(2).shape

torch.Size([226, 226, 1, 3])

In [ ]:
c.unsqueeze(0)

tensor([[[[0.8713, 0.0648, 0.4597],
          [0.7001, 0.5456, 0.9379],
          [0.7735, 0.3067, 0.0288],
          ...,
          [0.1679, 0.7026, 0.2474],
          [0.4765, 0.1622, 0.3424],
          [0.3077, 0.9497, 0.1641]],

         [[0.8906, 0.6174, 0.1665],
          [0.2636, 0.3008, 0.6062],
          [0.8872, 0.7250, 0.5632],
          ...,
          [0.6697, 0.9905, 0.0327],
          [0.0632, 0.3278, 0.9328],
          [0.4228, 0.2468, 0.5798]],

         [[0.7631, 0.7995, 0.8326],
          [0.5984, 0.3041, 0.9803],
          [0.0416, 0.8722, 0.9415],
          ...,
          [0.3593, 0.4594, 0.9320],
          [0.9534, 0.8105, 0.4385],
          [0.0342, 0.6590, 0.9808]],

         ...,

         [[0.2054, 0.1469, 0.5038],
          [0.3029, 0.2087, 0.4414],
          [0.0997, 0.8424, 0.5975],
          ...,
          [0.1474, 0.2429, 0.7641],
          [0.8260, 0.7502, 0.2584],
          [0.2267, 0.4827, 0.1979]],

         [[0.5549, 0.3148, 0.1151],
          [0.7420

In [ ]:
d = torch.rand(1,20)

In [ ]:
d

tensor([[0.3530, 0.8150, 0.5937, 0.1148, 0.4051, 0.7523, 0.6069, 0.4843, 0.4178,
         0.0459, 0.4060, 0.9441, 0.5357, 0.5787, 0.2253, 0.5833, 0.6302, 0.0835,
         0.6493, 0.3899]])

In [ ]:
d.squeeze(0)

tensor([0.3530, 0.8150, 0.5937, 0.1148, 0.4051, 0.7523, 0.6069, 0.4843, 0.4178,
        0.0459, 0.4060, 0.9441, 0.5357, 0.5787, 0.2253, 0.5833, 0.6302, 0.0835,
        0.6493, 0.3899])

In [ ]:
d.squeeze(0).shape

torch.Size([20])

In [ ]:
d.shape

torch.Size([1, 20])

In [ ]:
# Numpy and Pytorch

In [ ]:
import numpy as np

In [ ]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [ ]:
b = a.numpy()

In [ ]:
b

array([1, 2, 3])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
c = np.array([1,2,3])

In [ ]:
c

array([1, 2, 3])

In [ ]:
torch.from_numpy(c)

tensor([1, 2, 3])