In [2]:
!pip install torch

In [3]:
import torch

In [4]:
print(torch.__version__)

2.5.1+cpu


In [5]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. using CPU")

GPU not available. using CPU


### Creating a tensor

In [6]:
# using empty

torch.empty(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# check type
a = torch.empty(2,3)
type(a)

torch.Tensor

In [8]:
# using zeros

torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
# using ones

torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
# using rand

torch.rand(2,3)

tensor([[0.9760, 0.3638, 0.8979],
        [0.7759, 0.2926, 0.3377]])

In [11]:
# use of seed

torch.rand(2,3)

tensor([[0.7166, 0.8701, 0.0949],
        [0.6946, 0.8901, 0.0359]])

In [12]:
# manual seed

torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [13]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [14]:
# using tensor

torch.tensor([[1,2,3], [4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
torch.arange(1,10, 2)

tensor([1, 3, 5, 7, 9])

In [17]:
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [18]:
# identity matrix
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [19]:
torch.full((3,3), 5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

## Tensor shapes

In [20]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [21]:
x.shape

torch.Size([2, 3])

In [22]:
torch.empty_like(x)

tensor([[3448519133488,             0,             0],
        [            0,             0,             0]])

In [23]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [24]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [25]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

### Tensor Datatypes

In [26]:
x.dtype

torch.int64

In [27]:
# assign datatype

torch.tensor([1.0,2.0,3.0], dtype= torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [28]:
torch.tensor([1,2,3], dtype = torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [29]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [30]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

## Mathematical operations

In [31]:
# scalar operation

In [32]:
x = torch.rand(2,2)

In [33]:
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [34]:
# addition
x + 2

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])

In [35]:
# subtraction

x - 2

tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])

In [36]:
# multiplication

x*2

tensor([[1.4235, 1.5752],
        [0.8366, 1.8028]])

In [37]:
# division
x/3

tensor([[0.2373, 0.2625],
        [0.1394, 0.3005]])

In [38]:
# int division
(x*100)//3

tensor([[23., 26.],
        [13., 30.]])

In [39]:
# mod

((x*100)//3) % 2

tensor([[1., 0.],
        [1., 0.]])

In [40]:
# power
x ** 2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

In [41]:
## element wise operation

In [42]:
a = torch.rand(2,3)
b = torch.rand(2,3)

In [43]:
a

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])

In [44]:
b

tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])

In [45]:
# add

a + b

tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])

In [46]:
# sub

a - b

tensor([[ 0.4411, -0.2205, -0.2201],
        [-0.6455, -0.5661,  0.3346]])

In [47]:
a * b

tensor([[0.5540, 0.7391, 0.0994],
        [0.2866, 0.1328, 0.4030]])

In [48]:
a /b

tensor([[1.7938, 0.7743, 0.5042],
        [0.3190, 0.2397, 1.6841]])

In [49]:
# power

a **b

tensor([[0.9983, 0.7614, 0.5145],
        [0.3218, 0.2771, 0.9096]])

In [50]:
# mod

a%b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [51]:
c = torch.tensor([1,-2,3,-4])

In [52]:
c

tensor([ 1, -2,  3, -4])

In [53]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [54]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [55]:
d = torch.tensor([1.9,2.3,3.7,4.4])

In [56]:
d

tensor([1.9000, 2.3000, 3.7000, 4.4000])

In [57]:
torch.round(d)

tensor([2., 2., 4., 4.])

In [58]:
# ceil

torch.ceil(d)

tensor([2., 3., 4., 5.])

In [59]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [60]:
# clamp

torch.clamp(d, min = 2, max= 3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

In [61]:
## reduction operation

e = torch.randint(size=(2,3), low = 1, high = 10)
e

tensor([[7, 8, 8],
        [6, 7, 9]])

In [62]:
torch.sum(e)

tensor(45)

In [63]:
# sum along columns

torch.sum(e, dim = 0)

tensor([13, 15, 17])

In [64]:
torch.sum(e, dim = 1)

tensor([23, 22])

In [65]:
# mean

torch.mean(e, dtype=torch.float32)

tensor(7.5000)

In [66]:
torch.mean(e, dim = 0, dtype= torch.float32)

tensor([6.5000, 7.5000, 8.5000])

In [67]:
torch.median(e)

tensor(7)

In [68]:
torch.max(e)

tensor(9)

In [69]:
torch.min(e)

tensor(6)

In [70]:
torch.max(e, dim= 0)

torch.return_types.max(
values=tensor([7, 8, 9]),
indices=tensor([0, 0, 1]))

In [71]:
# product

torch.prod(e)

tensor(169344)

In [72]:
f = torch.randint(size=(2,3), low = 1, high = 10, dtype = torch.float32)
f

tensor([[3., 7., 7.],
        [4., 9., 3.]])

In [73]:
# standard deviation

torch.std(f)

tensor(2.5100)

In [74]:
# variance

torch.var(f)

tensor(6.3000)

In [75]:
# argmax

torch.argmax(e)

tensor(5)

In [76]:
# argmin

torch.argmin(e)

tensor(3)

### Matrix operations

In [77]:
g = torch.randint(size = (2,3), low = 1, high = 10)
h = torch.randint(size = (3,2), low = 1, high = 10)

In [78]:
g 

tensor([[7, 6, 7],
        [4, 1, 7]])

In [79]:
h

tensor([[5, 4],
        [7, 2],
        [1, 1]])

In [80]:
torch.matmul(g,h)

tensor([[84, 47],
        [34, 25]])

In [81]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

# dot product

torch.dot(vector1, vector2)

tensor(11)

In [82]:
torch.transpose(g,0, 1)

tensor([[7, 4],
        [6, 1],
        [7, 7]])

In [83]:
i = torch.randint(size = (3,3), low = 0, high=10, dtype= torch.float32)
i

tensor([[2., 6., 7.],
        [7., 8., 3.],
        [6., 1., 5.]])

In [84]:
# determinant

torch.det(i)

tensor(-315.)

In [86]:
# inverse

torch.inverse(i)

tensor([[-0.1175,  0.0730,  0.1206],
        [ 0.0540,  0.1016, -0.1365],
        [ 0.1302, -0.1079,  0.0825]])

### Comparison Operations

In [92]:
e

tensor([[7, 8, 8],
        [6, 7, 9]])

In [91]:
g

tensor([[7, 6, 7],
        [4, 1, 7]])

In [93]:
g > e

tensor([[False, False, False],
        [False, False, False]])

In [94]:
g < e

tensor([[False,  True,  True],
        [ True,  True,  True]])

In [95]:
g == e

tensor([[ True, False, False],
        [False, False, False]])

In [96]:
g >= e

tensor([[ True, False, False],
        [False, False, False]])

In [97]:
g <= e

tensor([[True, True, True],
        [True, True, True]])

In [98]:
g != e

tensor([[False,  True,  True],
        [ True,  True,  True]])

### Special functions

In [104]:
k = torch.randint(size = (2,3), low = 0, high = 10, dtype= torch.float32)
k

tensor([[3., 3., 5.],
        [0., 6., 4.]])

In [100]:
torch.log(k)

tensor([[1.6094,   -inf, 1.3863],
        [1.0986, 2.0794, 2.0794]])

In [101]:
torch.exp(k)

tensor([[1.4841e+02, 1.0000e+00, 5.4598e+01],
        [2.0086e+01, 2.9810e+03, 2.9810e+03]])

In [102]:
torch.sqrt(k)

tensor([[2.2361, 0.0000, 2.0000],
        [1.7321, 2.8284, 2.8284]])

In [103]:
torch.sigmoid(k)

tensor([[0.9933, 0.5000, 0.9820],
        [0.9526, 0.9997, 0.9997]])

In [106]:
torch.softmax(k, dim= 0) # for column

tensor([[0.9526, 0.0474, 0.7311],
        [0.0474, 0.9526, 0.2689]])

In [107]:
torch.relu(k)

tensor([[3., 3., 5.],
        [0., 6., 4.]])

### Inplace operations

In [119]:
## use _ to make permanent changes in variable

In [108]:
m = torch.rand(2,3)
n = torch.rand(2,3)

In [109]:
m

tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])

In [110]:
n

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

In [111]:
m + n

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [112]:
m.add(n)

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [113]:
m

tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])

In [114]:
m.add_(n)

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [115]:
m

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [117]:
m.relu_()

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [118]:
m

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

#### copying a Tensor

In [126]:
a = torch.rand(2,3)
a

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [127]:
b = a

In [128]:
b

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [129]:
a[0][0] = 0

In [130]:
a

tensor([[0.0000, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [131]:
b

tensor([[0.0000, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [132]:
id(a)

2419607052656

In [133]:
id(b)

2419607052656

In [134]:
b = a.clone()

In [135]:
a

tensor([[0.0000, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [136]:
b

tensor([[0.0000, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [137]:
a[0][0] = 10

In [138]:
a

tensor([[10.0000,  0.8935,  0.0497],
        [ 0.1780,  0.3011,  0.1893]])

In [139]:
b

tensor([[0.0000, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [140]:
id(a)

2419607052656

In [141]:
id(b)

2419607052816

### Tensor operations on GPU

In [144]:
torch.cuda.is_available()

False